language: ruby
bundler_args: --without yard guard benchmarks
script: "bundle exec rake metrics:coverage"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ruby-head
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
  email:
    on_success: never
    on_failure: change
