UncommunicativeParameterName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
TooManyMethods:
  max_methods: 12
  enabled: true
  exclude: []
  max_instance_variables: 3
UncommunicativeMethodName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
LongParameterList:
  enabled: true
  max_params: 2
  overrides: {}
  exclude:
    - ROM::Session::IdentityMap#store
FeatureEnvy:
  enabled: true
  exclude:
    - ROM::Session::ObjectNotTrackedError
    - ROM::Proxy
ClassVariable:
  exclude: []
  enabled: true
BooleanParameter:
  exclude: []
  enabled: true
IrresponsibleModule:
  exclude: []
  enabled: true
UncommunicativeModuleName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
NestedIterators:
  ignore_iterators: []
  exclude: []
  enabled: true
  max_allowed_nesting: 1
TooManyStatements:
  max_statements: 7
  exclude: []
  enabled: true
DuplicateMethodCall:
  allow_calls: []
  exclude: []
  enabled: false
  max_calls: 1
UtilityFunction:
  enabled: true
  max_helper_calls: 0
  exclude:
    - ROM::Session::ObjectNotTrackedError
    - ROM::Proxy
Attribute:
  exclude: []
  enabled: false
UncommunicativeVariableName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
RepeatedConditional:
  enabled: true
  max_ifs: 1
DataClump:
  enabled: true
  max_copies: 0
  min_clump_size: 2
  exclude:
    - ROM::Session::Tracker
ControlParameter:
  exclude: []
  enabled: true
LongYieldList:
  max_params: 0
  enabled: true
  exclude:
    - ROM::Session#self.start
